blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('blog/', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='blog_detail'),
]

native/urls.py
# Developed by Surfa
from unicodedata import name
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.urls import path
from native import views

app_name = 'native'

urlpatterns = [
    path('about/',views.About.as_view(),name='about'),
    path('contact/', views.contact_view, name='contact'),
    path('services/',views.Services.as_view(),name='services'),
    path('gallery/',views.Gallery.as_view(),name='gallery'),
    path('team/',views.Team.as_view(),name='team'),
    path('timetable/',views.Timetable.as_view(),name='timetable'),
    path('bmi/',views.bmi,name='bmi'),
    path('classdetail/',views.ClassDetail.as_view(),name='classdetail'),
    path('blog/', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='blog_detail'),
]

native_web/urls.py
# Developed by Surfa
"""native_web URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path
from native import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('',
         include('native.urls')),
    path('blog/',
         include('blog.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls))
    ]+urlpatterns

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to='featured_image/%Y/%m/%d')
    
    class Meta:
        ordering = ['-created_on']
        
    def __str__(self):
        return self.title
    

class Galary(models.Model):
    title = models.ImageField(upload_to='images')
    jpeg = models.ImageField(upload_to='images')
    
    def __str__(self):
        return self.title

native/models.py
# Developed by Surfa
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"publish")
)

class Trainers(models.Model):
    title = models.CharField(max_length=200, unique=False)
    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    fb_account = models.CharField(max_length=200, unique=True)
    youtube_account = models.CharField(max_length=200, unique=True)
    insta_account = models.CharField(max_length=200, unique=True)
    twitter_account = models.CharField(max_length=200, unique=True)
    trainer_email = models.CharField(max_length=200, unique=True)
    
    def __str__(self):
        return self.title


class Gallery(models.Model):
    title = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    image2 = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    
    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=200, unique=True)
    email = models.CharField(max_length=200, unique=True)
    website =  models.CharField(max_length=200, unique=True)
    message = models.TextField(max_length=200, unique=True)
    
    def __str__(self):
        return self.name

User = get_user_model()

class Bmi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    weight = models.FloatField()
    height = models.FloatField()
    bmi = models.FloatField()
    date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.user
    

native/forms.py
# Developed by Surfa
from django import forms
from operator import mod
from pyexpat import model
from django import forms
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from native.models import Contact



# class ImageForm(forms.ModelForm):
#     """Form for the image model"""
#     class Meta:
#         model = Galary
#         fields = ('title', 'image2')



class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
    
    # def send_name(self):
    #     # send email using the self.cleaned_data dictionary
    #     name = self.cleaned_data['name'].lower()
    #     r = Contact.objects.filter(name=name)
    #     if r.count():
    #         raise  ValidationError("Username already exists")
    #     return name
    
    # def send_email(self):
    #     email = self.cleaned_data['email'].lower()
    #     r = Contact.objects.filter(email=email)
    #     if r.count():
    #         raise  ValidationError("Email already exists")
    #     return email
    
    # def send_website(self):
    #     website = self.cleaned_data['website'].lower()
    #     r = Contact.objects.filter(website=website)
    #     if r.count():
    #         raise  ValidationError("Email already exists")
    #     return website
    




# class UserCreatForm(UserCreationForm):
    
#     class Meta:
#         fields = ('name', 'email', 'website','comment')
#         model = get_user_model()
        
#         def __init__(self,*args,**kwargs):
#             super().__init__(*args,**kwargs)
#             self.fields['name'].lebel= 'First Name'
#             self.fields['email'].lebel = 'Email Address'
#             self.fields['website'].lebel = 'website'
#             self.fields['comment'].lebel = 'comment' 

# class Contact(forms.Form):
#     name = models.CharField(max_length=200, unique=True)
#     email = models.EmailField(max_length=200, unique=True)
#     website =  models.CharField(max_length=200, unique=True)
#     message = models.TextField(max_length=2000, unique=False)

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
# Create your views here.

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/blog.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/blog-details.html'

native/views.py
# Developed by Surfa

from email import message_from_string
from django.conf import settings
from telnetlib import GA
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from django.views import generic
from blog.models import Post
from native.models import Gallery, Trainers, Bmi
from native.forms import ContactForm
from django.views.generic.edit import FormView
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.

class HomePage(generic.ListView):
    queryset = Trainers.objects.all()
    template_name = 'index.html'


# send with sengrid

# def contact_view(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             email_subject = f'New contact {form.cleaned_data["email"]}: {form.cleaned_data["subject"]}'
#             email_message = form.cleaned_data['message']
#             send_mail(email_subject, email_message, settings.CONTACT_EMAIL, settings.ADMIN_EMAIL)
#             return render(request, 'contact.html')
#     form = ContactForm()
#     context = {'form': form}
#     return render(request, 'contact.html', context)


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contact request submitted successfully.')
            return render(request, 'contact.html', {'form': ContactForm(request.GET)})
        else:
            messages.error(request, 'Invalid form submission.')
            messages.error(request, form.errors)
    form = ContactForm()
    context = {'form': form}
    return render(request, 'contact.html', context)




class Services(TemplateView):
    template_name = 'services.html'



class Gallery(generic.ListView):
    queryset = Gallery.objects.all()
    template_name = 'gallery.html'


class Team(generic.ListView):
    queryset = Trainers.objects.all()
    template_name = 'team.html'

class Timetable(TemplateView):
    template_name = 'class-timetable.html'

class ClassDetail(TemplateView):
    template_name = 'class-details.html'


class BMI(TemplateView):
    template_name  = 'bmi-calculator.html'


#class Blog(DetailView):
    #queryset = Post.objects.filter(status=1).order_by('-created_on')
    #def get_queryset(self):
        #return super().get_queryset()
    
    #template_name = 'blog.html'


#class BlogDetail(DetailView):
    #template_name = 'blog-details.html'


class About(generic.ListView):
    queryset = Trainers.objects.all()
    template_name = 'about-us.html'
    



class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/post_index.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


def bmi(request):
    context = {}
    if request.method=="POST":
        weight_metric = request.POST.get("weight-metric")
        weight_imperial = request.POST.get("weight-imperial")
        if weight_metric:
            weight = float(request.POST.get("weight-metric"))
            height = float(request.POST.get("height-metric"))
        elif weight_imperial:
            weight = float(request.POST.get("weight-imperial"))/2.205
            height = (float(request.POST.get("feet"))*30.48 + float(request.POST.get("inches"))*2.54)/100
        bmi = (weight/(height**2))
        save = request.POST.get("save")
        if save == "on":
            Bmi.objects.create(user=request.user,weight=weight, height=height, bmi=round(bmi))
        if bmi < 16:
            state = "Severe Thinness"
        elif bmi > 16 and bmi < 17:
            state = "Moderate Thinness"
        elif bmi > 17 and bmi < 18:
            state = "Mild Thinness"
        elif bmi > 18 and bmi < 25:
            state = "Normal"
        elif bmi > 25 and bmi < 30:
            state = "Overweight"
        elif bmi > 30 and bmi < 35:
            state = "Obese Class I"
        elif bmi > 35 and bmi < 40:
            state = "Obese Class II"
        elif bmi > 40:
            state = "Obese Class III"
        context["bmi"] = round(bmi)
        context["state"] = state
    return render(request, "bmi-calculator.html", context)

native/templates/about-us.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static "img/breadcrumb-bg.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>About us</h2>
                        <div class="bt-option">
                            <a href="{% url 'home' %}">Home</a>
                            <span>About</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- ChoseUs Section Begin -->
    <section class="choseus-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>Why chose us?</span>
                        <h2>PUSH YOUR LIMITS FORWARD</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
                        <span class="flaticon-034-stationary-bike"></span>
                        <h4>Modern equipment</h4>
                        <p>Modern Gym & Fitness Facilities. Cycle your way to the ultimate fitness results. 
                            Rides are set to a motivational soundtrack and may vary and blend technique, 
                            intervals, resistance rides, climbs and sprints for a fun, 
                            challenging and rewarding cardio experience.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
                        <span class="flaticon-033-juice"></span>
                        <h4>Healthy nutrition plan</h4>
                        <p>Healthy nutrition plan Nutrition and weight loss, simplified Discover ways to make 
                            healthy living easier with our Nutrition.
                            Yoga, is a meditative means of discovering dysfunctional perception and cognition,
                            as well as overcoming it for release from suffering, inner peace and salvation.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
                        <span class="flaticon-002-dumbell"></span>
                        <h4>Professional training plan</h4>
                        <p>Healthy nutrition plan.Yoga, is a meditative means of discovering dysfunctional perception and cognition,
                            as well as overcoming it for release from suffering, inner peace and salvation.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="cs-item">
                        <span class="flaticon-014-heart-beat"></span>
                        <h4>Unique to your needs</h4>
                        <p>Training is going to consist of 8 to 12 or 12 to 15 reps for 3 to 6 sets with 45 to 90 seconds of rests. 
                            Bodybuilders often “display” their hard work by posing onstage in front of a panel of judges.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ChoseUs Section End -->

    <!-- About US Section Begin -->
    <section class="aboutus-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 p-0">
                    <div class="about-video set-bg" data-setbg="{% static "img/about-us.jpg" %}">
                        <a href="https://www.youtube-nocookie.com/embed/Er7Xp1oecLo" class="play-btn video-popup"><i
                                class="fa fa-caret-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-6 p-0">
                    <div class="about-text">
                        <div class="section-title">
                            <span>About Us</span>
                            <h2>What we have done</h2>
                        </div>
                        <div class="at-desc">
                            <p>Bodybuilding focuses on hypertrophy, or muscle growth. 
                                Each workout typically focuses on a specific muscle group and incorporates more single-joint exercises such as bicep curls. 
                                Training is going to consist of 8 to 12 or 12 to 15 reps for 3 to 6 sets with 45 to 90 seconds of rests. 
                                Bodybuilders often “display” their hard work by posing onstage in front of a panel of judges.
                                Native gym is ready and willing to help people with every step of their fitness journey,
                                Native Fitness is a comprehensive resource that’s motivating and inspiring...</p>
                        </div>
                        <div class="about-bar">
                            <div class="ab-item">
                                <p>Body building</p>
                                <div id="bar1" class="barfiller">
                                    <span class="fill" data-percentage="80"></span>
                                    <div class="tipWrap">
                                        <span class="tip"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="ab-item">
                                <p>Training</p>
                                <div id="bar2" class="barfiller">
                                    <span class="fill" data-percentage="85"></span>
                                    <div class="tipWrap">
                                        <span class="tip"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="ab-item">
                                <p>Fitness</p>
                                <div id="bar3" class="barfiller">
                                    <span class="fill" data-percentage="75"></span>
                                    <div class="tipWrap">
                                        <span class="tip"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About US Section End -->
    <!-- Team Section Begin -->
    <section class="team-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="team-title">
                        <div class="section-title">
                            <span>Our Team</span>
                            <h2>TRAIN WITH EXPERTS</h2>
                        </div>
                        <a href="/contact" class="primary-btn btn-normal appoinment-btn">appointment</a>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for trainers in trainers_list %}
                <div class="col-lg-4 col-sm-6">
                    <div class="ts-item set-bg" data-setbg="{{ trainers.image.url }}">
                        <div class="ts_text">
                            <h4>{{ trainers.name}}</h4>
                            <span>{{trainers.title}}</span>
                            <div class="tt_social">
                                <a href="{{ trainers.fb_account}}"><i class="fa fa-facebook"></i></a>
                                <a href="{{ trainers.twitter_account}}"><i class="fa fa-twitter"></i></a>
                                <a href="{{ trainers.youtube_account}}"><i class="fa fa-youtube-play"></i></a>
                                <a href="{{ trainers.insta_account}}"><i class="fa fa-instagram"></i></a>
                                <a href="{{ trainers.trainer_email}}"><i class="fa  fa-envelope-o"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Team Section End -->

    <!-- Banner Section Begin -->
    <section class="banner-section set-bg" data-setbg="{% static "img/bn5.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="bs-text">
                        <h2>register now to get more deals</h2>
                        <div class="bt-tips">Where health, beauty and fitness meet.</div>
                        <a href="/contact" class="primary-btn  btn-normal">Appointment</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Banner Section End -->

    <!-- Testimonial Section Begin -->
    <section class="testimonial-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>Testimonial</span>
                        <h2>Our cilent say</h2>
                    </div>
                </div>
            </div>
            <div class="ts_slider owl-carousel">
                <div class="ts_item">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="ti_pic">
                                <img src="#" alt="client">
                            </div>
                            <div class="ti_text">
                                <p>“For my three years of being a member here, what I enjoy most is the friendly environment, <br /> 
                                    the functional fitness equipment, <br /> how neat the place is and the kind of activities and classes run here."</p>
                                <h5>-----</h5>
                                <div class="tt-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ts_item">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="ti_pic">
                                <img src="#" alt="client">
                            </div>
                            <div class="ti_text">
                                <p>The gym is well equipped Good management Motivation is always peaked Loved the place ✌<br /> <br />
                                    The gym is with wonders As you will see changes within a month.</p>
                                <h5>------</h5>
                                <div class="tt-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Testimonial Section End -->
    {% block footer %}
    {% include 'footer.html' %}
    {% endblock footer %}

    {% endblock content %}

native/templates/gallery.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static "img/breadcrumb-bg.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Gallery</h2>
                        <div class="bt-option">
                            <a href="{% url 'home' %}">Home</a>
                            <a href="#">Pages</a>
                            <span>Gallery</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Gallery Section Begin -->
    <div class="gallery-section">
        <div class="gallery">
            {% for gallery in gallery_list %}
            <div class="grid-sizer"></div>
            <div class="gs-item grid-wide set-bg" data-setbg="{{ gallery.image.url }}">
                <a href="{{ gallery.image.url }}" class="thumb-icon image-popup"><i class="fa fa-picture-o"></i></a>
            </div>
            <div class="gs-item set-bg" data-setbg="{{ gallery.image2.url }}">
                <a href="{{ gallery.image2.url }}" class="thumb-icon image-popup"><i class="fa fa-picture-o"></i></a>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- Gallery Section End -->

    {% block footer %}
    {% include 'footer.html' %}
    {% endblock footer %}


    {% endblock content %}

native/templates/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    {{ message }}
    </div>
</div>
{% endfor %}

native/templates/team.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static "img/breadcrumb-bg.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Our Team</h2>
                        <div class="bt-option">
                            <a href="{% url 'home' %}">Home</a>
                            <span>Our team</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Team Section Begin -->
    <section class="team-section team-page spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="team-title">
                        <div class="section-title">
                            <span>Our Team</span>
                            <h2>TRAIN WITH EXPERTS</h2>
                        </div>
                        <a href="/contact" class="primary-btn btn-normal appoinment-btn">appointment</a>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for trainers in trainers_list %}
                <div class="col-lg-4 col-sm-6">
                    <div class="ts-item set-bg" data-setbg="{{ trainers.image.url }}">
                        <div class="ts_text">
                            <h4>{{ trainers.name}}</h4>
                            <span>{{trainers.title}}</span>
                            <div class="tt_social">
                                <a href="{{ trainers.fb_account}}"><i class="fa fa-facebook"></i></a>
                                <a href="{{ trainers.twitter_account}}"><i class="fa fa-twitter"></i></a>
                                <a href="{{ trainers.youtube_account}}"><i class="fa fa-youtube-play"></i></a>
                                <a href="{{ trainers.insta_account}}"><i class="fa fa-instagram"></i></a>
                                <a href="{{ trainers.trainer_email}}"><i class="fa  fa-envelope-o"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Team Section End -->

    {% block footer %}
    {% include 'footer.html' %}
    {% endblock footer %}

    {% endblock content %}