blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('blog/', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='blog_detail'),
]

native_web/urls.py
# Developed by Surfa
"""native_web URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.urls import path
from native import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('',
         include('native.urls')),
    path('blog/',
         include('blog.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls))
    ]+urlpatterns

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to='featured_image/%Y/%m/%d')
    
    class Meta:
        ordering = ['-created_on']
        
    def __str__(self):
        return self.title
    

class Galary(models.Model):
    title = models.ImageField(upload_to='images')
    jpeg = models.ImageField(upload_to='images')
    
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
# Create your views here.

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/blog.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/blog-details.html'

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

    <!-- Blog Details Hero Section Begin -->
    <section class="blog-details-hero set-bg" data-setbg="{% static "img/blog/details/details-hero.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 p-0 m-auto">
                    <div class="bh-text">
                        <h3>Workout nutrition explained. What to eat before, during, and after exercise.</h3>
                        <ul>
                            <li>{{ post.author }}</li>
                            <li>{{ post.created_on }}</li>
                            <li>20 Comment</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Our Blog</h2>
                        <div class="bt-option">
                            <a href="{% url 'home' %}">Home</a>
                            <a href="#">Pages</a>
                            <a href="/blog">blog</a>
                            <span>Blog Detail</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero Section End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 p-0 m-auto">
                    <div class="blog-details-text">
                        <div class="blog-details-title">
                            <div class="cards-body">
                                <img src="{{ post.image.url }}" class="rounded featured-image-list" alt="{{post.title}}">
                                <h5>{% block title %} {{ object.title }} {% endblock title %}</h1>
                                <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
                                <p class="cards-text ">{{ object.content | safe }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Get In Touch Section End -->

    {% block footer %}
    {% include 'footer.html' %}
    {% endblock footer %}
    {% endblock content %}

blog/templates/blog/post_index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static "img/breadcrumb-bg.jpg" %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb-text">
                        <h2>Our Blog</h2>
                        <div class="bt-option">
                            <a href="{% url 'home' %}">Home</a>
                            <a href="#">Pages</a>
                            <span>Blog</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Blog Section Begin -->
    <section class="blog-section spad">
        <div class="container">
            <div class="row">
                <div class="col-md-8 mt-3 left">
                    {% for post in post_list %}
                    <div class="blog-item">
                        <div class="bi-pic">
                            <img src="{{ post.image.url }}" class="rounded featured-image-list" alt="{{post.title}}">
                        </div>
                        <div class="bi-text">
                            <h5>{{ post.title }}
                                    </h5>
                            <ul>
                                <li>{{ post.author }}</li>
                                <li>{{ post.created_on}}</li>
                                
                            </ul>
                            <p>{{post.content|slice:":200" }}
                                </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-lg-4 col-md-8 p-0">
                    <div class="sidebar-option">
                        <div class="so-categories">
                            <h5 class="title">Categories</h5>
                            <ul>
                                <li><a href="#">Yoga <span>12</span></a></li>
                                <li><a href="#">Runing <span>32</span></a></li>
                                <li><a href="#">Weightloss <span>86</span></a></li>
                                <li><a href="#">Cario <span>25</span></a></li>
                                <li><a href="#">Body buiding <span>36</span></a></li>
                                <li><a href="#">Nutrition <span>15</span></a></li>
                            </ul>
                        </div>
                        <div class="so-latest">
                            <h5 class="title">Feature posts</h5>
                            <div class="latest-large set-bg" data-setbg="{% static "img/letest-blog/latest-1.jpg" %}">
                                <div class="ll-text">
                                    <h5><a href="https://blog.feedspot.com/fitness_blogs/">This Japanese Way of Making Iced Coffee Is a Game...</a></h5>
                                    <ul>
                                        <li><span class="li-time">Aug 15,<script>document.write(new Date().getFullYear());</script></span></li>
                                        <li>20 Comment</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="latest-item">
                                <div class="li-pic">
                                    <img src="{% static "img/letest-blog/latest-2.jpg" %}" alt="">
                                </div>
                                <div class="li-text">
                                    <h6><a href="https://blog.feedspot.com/fitness_blogs/">Grilled Potato and Green Bean Salad</a></h6>
                                    <span class="li-time">June 22,<script>document.write(new Date().getFullYear());</script></span>
                                </div>
                            </div>
                            <div class="latest-item">
                                <div class="li-pic">
                                    <img src="{% static "img/letest-blog/latest-3.jpg" %}" alt="">
                                </div>
                                <div class="li-text">
                                    <h6><a href="https://blog.feedspot.com/fitness_blogs/">The $8 French Rosé I Buy in Bulk Every Summer</a></h6>
                                    <span class="li-time">May 10,<script>document.write(new Date().getFullYear());</script></span>
                                </div>
                            </div>
                            <div class="latest-item">
                                <div class="li-pic">
                                    <img src="{% static "img/letest-blog/latest-4.jpg" %}" alt="">
                                </div>
                                <div class="li-text">
                                    <h6><a href="https://blog.feedspot.com/fitness_blogs/">Ina Garten's Skillet-Roasted Lemon Chicken</a></h6>
                                    <span class="li-time">Aug 15,<script>document.write(new Date().getFullYear());</script></span>
                                </div>
                            </div>
                            <div class="latest-item">
                                <div class="li-pic">
                                    <img src="{% static "img/letest-blog/latest-5.jpg" %}" alt="">
                                </div>
                                <div class="li-text">
                                    <h6><a href="https://blog.feedspot.com/fitness_blogs/">The Best Weeknight Baked Potatoes, 3 Creative Ways</a></h6>
                                    <span class="li-time">Aug 17,<script>document.write(new Date().getFullYear());</script></span>
                                </div>
                            </div>
                        </div>
                        <div class="so-tags">
                            <h5 class="title">Popular tags</h5>
                            <a href="#">Gyming</a>
                            <a href="#">Body buidling</a>
                            <a href="#">Yoga</a>
                            <a href="#">Weightloss</a>
                            <a href="#">Proffeponal</a>
                            <a href="#">Streching</a>
                            <a href="#">Cardio</a>
                            <a href="#">Karate</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->

    {% block footer %}
    {% include 'footer.html' %}
    {% endblock footer %}



    {% endblock content %}